
# load .env file
set dotenv-load
# causes all just variables to be exported
set export

default:
  @just --list

cls:
    # echo "\033[H\033[J"
    # tput reset
    clear && printf '\e[3J'

dev:
  bun --watch server.ts

getCommits: cls
  bun cli.ts getCommits

getReview: cls
  bun cli.ts getReview

