
# load .env file
set dotenv-load
# causes all just variables to be exported
set export

default:
  @just --list

dev:
  bun --watch server.ts

getCommits:
  bun cli.ts getCommits

getReview:
  bun cli.ts getReview

cls:
    # echo "\033[H\033[J"
    # tput reset
    clear && printf '\e[3J'
